// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: cores/cable_service.proto

package cores

import (
	context "context"
	pb "github.com/snple/kokomi/pb"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	CableService_Create_FullMethodName          = "/cores.CableService/Create"
	CableService_Update_FullMethodName          = "/cores.CableService/Update"
	CableService_View_FullMethodName            = "/cores.CableService/View"
	CableService_Name_FullMethodName            = "/cores.CableService/Name"
	CableService_NameFull_FullMethodName        = "/cores.CableService/NameFull"
	CableService_Delete_FullMethodName          = "/cores.CableService/Delete"
	CableService_List_FullMethodName            = "/cores.CableService/List"
	CableService_Link_FullMethodName            = "/cores.CableService/Link"
	CableService_Clone_FullMethodName           = "/cores.CableService/Clone"
	CableService_ViewWithDeleted_FullMethodName = "/cores.CableService/ViewWithDeleted"
	CableService_Pull_FullMethodName            = "/cores.CableService/Pull"
	CableService_Sync_FullMethodName            = "/cores.CableService/Sync"
)

// CableServiceClient is the client API for CableService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CableServiceClient interface {
	Create(ctx context.Context, in *pb.Cable, opts ...grpc.CallOption) (*pb.Cable, error)
	Update(ctx context.Context, in *pb.Cable, opts ...grpc.CallOption) (*pb.Cable, error)
	View(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.Cable, error)
	Name(ctx context.Context, in *CableNameRequest, opts ...grpc.CallOption) (*pb.Cable, error)
	NameFull(ctx context.Context, in *pb.Name, opts ...grpc.CallOption) (*pb.Cable, error)
	Delete(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.MyBool, error)
	List(ctx context.Context, in *CableListRequest, opts ...grpc.CallOption) (*CableListResponse, error)
	Link(ctx context.Context, in *CableLinkRequest, opts ...grpc.CallOption) (*pb.MyBool, error)
	Clone(ctx context.Context, in *CableCloneRequest, opts ...grpc.CallOption) (*pb.MyBool, error)
	ViewWithDeleted(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.Cable, error)
	Pull(ctx context.Context, in *CablePullRequest, opts ...grpc.CallOption) (*CablePullResponse, error)
	Sync(ctx context.Context, in *pb.Cable, opts ...grpc.CallOption) (*pb.MyBool, error)
}

type cableServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCableServiceClient(cc grpc.ClientConnInterface) CableServiceClient {
	return &cableServiceClient{cc}
}

func (c *cableServiceClient) Create(ctx context.Context, in *pb.Cable, opts ...grpc.CallOption) (*pb.Cable, error) {
	out := new(pb.Cable)
	err := c.cc.Invoke(ctx, CableService_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cableServiceClient) Update(ctx context.Context, in *pb.Cable, opts ...grpc.CallOption) (*pb.Cable, error) {
	out := new(pb.Cable)
	err := c.cc.Invoke(ctx, CableService_Update_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cableServiceClient) View(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.Cable, error) {
	out := new(pb.Cable)
	err := c.cc.Invoke(ctx, CableService_View_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cableServiceClient) Name(ctx context.Context, in *CableNameRequest, opts ...grpc.CallOption) (*pb.Cable, error) {
	out := new(pb.Cable)
	err := c.cc.Invoke(ctx, CableService_Name_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cableServiceClient) NameFull(ctx context.Context, in *pb.Name, opts ...grpc.CallOption) (*pb.Cable, error) {
	out := new(pb.Cable)
	err := c.cc.Invoke(ctx, CableService_NameFull_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cableServiceClient) Delete(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.MyBool, error) {
	out := new(pb.MyBool)
	err := c.cc.Invoke(ctx, CableService_Delete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cableServiceClient) List(ctx context.Context, in *CableListRequest, opts ...grpc.CallOption) (*CableListResponse, error) {
	out := new(CableListResponse)
	err := c.cc.Invoke(ctx, CableService_List_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cableServiceClient) Link(ctx context.Context, in *CableLinkRequest, opts ...grpc.CallOption) (*pb.MyBool, error) {
	out := new(pb.MyBool)
	err := c.cc.Invoke(ctx, CableService_Link_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cableServiceClient) Clone(ctx context.Context, in *CableCloneRequest, opts ...grpc.CallOption) (*pb.MyBool, error) {
	out := new(pb.MyBool)
	err := c.cc.Invoke(ctx, CableService_Clone_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cableServiceClient) ViewWithDeleted(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.Cable, error) {
	out := new(pb.Cable)
	err := c.cc.Invoke(ctx, CableService_ViewWithDeleted_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cableServiceClient) Pull(ctx context.Context, in *CablePullRequest, opts ...grpc.CallOption) (*CablePullResponse, error) {
	out := new(CablePullResponse)
	err := c.cc.Invoke(ctx, CableService_Pull_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cableServiceClient) Sync(ctx context.Context, in *pb.Cable, opts ...grpc.CallOption) (*pb.MyBool, error) {
	out := new(pb.MyBool)
	err := c.cc.Invoke(ctx, CableService_Sync_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CableServiceServer is the server API for CableService service.
// All implementations must embed UnimplementedCableServiceServer
// for forward compatibility
type CableServiceServer interface {
	Create(context.Context, *pb.Cable) (*pb.Cable, error)
	Update(context.Context, *pb.Cable) (*pb.Cable, error)
	View(context.Context, *pb.Id) (*pb.Cable, error)
	Name(context.Context, *CableNameRequest) (*pb.Cable, error)
	NameFull(context.Context, *pb.Name) (*pb.Cable, error)
	Delete(context.Context, *pb.Id) (*pb.MyBool, error)
	List(context.Context, *CableListRequest) (*CableListResponse, error)
	Link(context.Context, *CableLinkRequest) (*pb.MyBool, error)
	Clone(context.Context, *CableCloneRequest) (*pb.MyBool, error)
	ViewWithDeleted(context.Context, *pb.Id) (*pb.Cable, error)
	Pull(context.Context, *CablePullRequest) (*CablePullResponse, error)
	Sync(context.Context, *pb.Cable) (*pb.MyBool, error)
	mustEmbedUnimplementedCableServiceServer()
}

// UnimplementedCableServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCableServiceServer struct {
}

func (UnimplementedCableServiceServer) Create(context.Context, *pb.Cable) (*pb.Cable, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedCableServiceServer) Update(context.Context, *pb.Cable) (*pb.Cable, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedCableServiceServer) View(context.Context, *pb.Id) (*pb.Cable, error) {
	return nil, status.Errorf(codes.Unimplemented, "method View not implemented")
}
func (UnimplementedCableServiceServer) Name(context.Context, *CableNameRequest) (*pb.Cable, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Name not implemented")
}
func (UnimplementedCableServiceServer) NameFull(context.Context, *pb.Name) (*pb.Cable, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NameFull not implemented")
}
func (UnimplementedCableServiceServer) Delete(context.Context, *pb.Id) (*pb.MyBool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedCableServiceServer) List(context.Context, *CableListRequest) (*CableListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedCableServiceServer) Link(context.Context, *CableLinkRequest) (*pb.MyBool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Link not implemented")
}
func (UnimplementedCableServiceServer) Clone(context.Context, *CableCloneRequest) (*pb.MyBool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Clone not implemented")
}
func (UnimplementedCableServiceServer) ViewWithDeleted(context.Context, *pb.Id) (*pb.Cable, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ViewWithDeleted not implemented")
}
func (UnimplementedCableServiceServer) Pull(context.Context, *CablePullRequest) (*CablePullResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Pull not implemented")
}
func (UnimplementedCableServiceServer) Sync(context.Context, *pb.Cable) (*pb.MyBool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sync not implemented")
}
func (UnimplementedCableServiceServer) mustEmbedUnimplementedCableServiceServer() {}

// UnsafeCableServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CableServiceServer will
// result in compilation errors.
type UnsafeCableServiceServer interface {
	mustEmbedUnimplementedCableServiceServer()
}

func RegisterCableServiceServer(s grpc.ServiceRegistrar, srv CableServiceServer) {
	s.RegisterService(&CableService_ServiceDesc, srv)
}

func _CableService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Cable)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CableServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CableService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CableServiceServer).Create(ctx, req.(*pb.Cable))
	}
	return interceptor(ctx, in, info, handler)
}

func _CableService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Cable)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CableServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CableService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CableServiceServer).Update(ctx, req.(*pb.Cable))
	}
	return interceptor(ctx, in, info, handler)
}

func _CableService_View_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CableServiceServer).View(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CableService_View_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CableServiceServer).View(ctx, req.(*pb.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _CableService_Name_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CableNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CableServiceServer).Name(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CableService_Name_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CableServiceServer).Name(ctx, req.(*CableNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CableService_NameFull_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Name)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CableServiceServer).NameFull(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CableService_NameFull_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CableServiceServer).NameFull(ctx, req.(*pb.Name))
	}
	return interceptor(ctx, in, info, handler)
}

func _CableService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CableServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CableService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CableServiceServer).Delete(ctx, req.(*pb.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _CableService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CableListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CableServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CableService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CableServiceServer).List(ctx, req.(*CableListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CableService_Link_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CableLinkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CableServiceServer).Link(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CableService_Link_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CableServiceServer).Link(ctx, req.(*CableLinkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CableService_Clone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CableCloneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CableServiceServer).Clone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CableService_Clone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CableServiceServer).Clone(ctx, req.(*CableCloneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CableService_ViewWithDeleted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CableServiceServer).ViewWithDeleted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CableService_ViewWithDeleted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CableServiceServer).ViewWithDeleted(ctx, req.(*pb.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _CableService_Pull_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CablePullRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CableServiceServer).Pull(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CableService_Pull_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CableServiceServer).Pull(ctx, req.(*CablePullRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CableService_Sync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Cable)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CableServiceServer).Sync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CableService_Sync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CableServiceServer).Sync(ctx, req.(*pb.Cable))
	}
	return interceptor(ctx, in, info, handler)
}

// CableService_ServiceDesc is the grpc.ServiceDesc for CableService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CableService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cores.CableService",
	HandlerType: (*CableServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _CableService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _CableService_Update_Handler,
		},
		{
			MethodName: "View",
			Handler:    _CableService_View_Handler,
		},
		{
			MethodName: "Name",
			Handler:    _CableService_Name_Handler,
		},
		{
			MethodName: "NameFull",
			Handler:    _CableService_NameFull_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _CableService_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _CableService_List_Handler,
		},
		{
			MethodName: "Link",
			Handler:    _CableService_Link_Handler,
		},
		{
			MethodName: "Clone",
			Handler:    _CableService_Clone_Handler,
		},
		{
			MethodName: "ViewWithDeleted",
			Handler:    _CableService_ViewWithDeleted_Handler,
		},
		{
			MethodName: "Pull",
			Handler:    _CableService_Pull_Handler,
		},
		{
			MethodName: "Sync",
			Handler:    _CableService_Sync_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cores/cable_service.proto",
}

const (
	WireService_Create_FullMethodName                  = "/cores.WireService/Create"
	WireService_Update_FullMethodName                  = "/cores.WireService/Update"
	WireService_View_FullMethodName                    = "/cores.WireService/View"
	WireService_Name_FullMethodName                    = "/cores.WireService/Name"
	WireService_NameFull_FullMethodName                = "/cores.WireService/NameFull"
	WireService_Delete_FullMethodName                  = "/cores.WireService/Delete"
	WireService_List_FullMethodName                    = "/cores.WireService/List"
	WireService_Clone_FullMethodName                   = "/cores.WireService/Clone"
	WireService_GetValue_FullMethodName                = "/cores.WireService/GetValue"
	WireService_SetValue_FullMethodName                = "/cores.WireService/SetValue"
	WireService_SetValueUnchecked_FullMethodName       = "/cores.WireService/SetValueUnchecked"
	WireService_GetValueByName_FullMethodName          = "/cores.WireService/GetValueByName"
	WireService_SetValueByName_FullMethodName          = "/cores.WireService/SetValueByName"
	WireService_SetValueByNameUnchecked_FullMethodName = "/cores.WireService/SetValueByNameUnchecked"
	WireService_ViewWithDeleted_FullMethodName         = "/cores.WireService/ViewWithDeleted"
	WireService_Pull_FullMethodName                    = "/cores.WireService/Pull"
	WireService_Sync_FullMethodName                    = "/cores.WireService/Sync"
	WireService_ViewValue_FullMethodName               = "/cores.WireService/ViewValue"
	WireService_DeleteValue_FullMethodName             = "/cores.WireService/DeleteValue"
	WireService_PullValue_FullMethodName               = "/cores.WireService/PullValue"
	WireService_SyncValue_FullMethodName               = "/cores.WireService/SyncValue"
)

// WireServiceClient is the client API for WireService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WireServiceClient interface {
	Create(ctx context.Context, in *pb.Wire, opts ...grpc.CallOption) (*pb.Wire, error)
	Update(ctx context.Context, in *pb.Wire, opts ...grpc.CallOption) (*pb.Wire, error)
	View(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.Wire, error)
	Name(ctx context.Context, in *WireNameRequest, opts ...grpc.CallOption) (*pb.Wire, error)
	NameFull(ctx context.Context, in *pb.Name, opts ...grpc.CallOption) (*pb.Wire, error)
	Delete(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.MyBool, error)
	List(ctx context.Context, in *WireListRequest, opts ...grpc.CallOption) (*WireListResponse, error)
	Clone(ctx context.Context, in *WireCloneRequest, opts ...grpc.CallOption) (*pb.MyBool, error)
	GetValue(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.WireValue, error)
	SetValue(ctx context.Context, in *pb.WireValue, opts ...grpc.CallOption) (*pb.MyBool, error)
	SetValueUnchecked(ctx context.Context, in *pb.WireValue, opts ...grpc.CallOption) (*pb.MyBool, error)
	GetValueByName(ctx context.Context, in *WireGetValueByNameRequest, opts ...grpc.CallOption) (*WireNameValue, error)
	SetValueByName(ctx context.Context, in *WireNameValue, opts ...grpc.CallOption) (*pb.MyBool, error)
	SetValueByNameUnchecked(ctx context.Context, in *WireNameValue, opts ...grpc.CallOption) (*pb.MyBool, error)
	ViewWithDeleted(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.Wire, error)
	Pull(ctx context.Context, in *WirePullRequest, opts ...grpc.CallOption) (*WirePullResponse, error)
	Sync(ctx context.Context, in *pb.Wire, opts ...grpc.CallOption) (*pb.MyBool, error)
	ViewValue(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.WireValueUpdated, error)
	DeleteValue(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.MyBool, error)
	PullValue(ctx context.Context, in *WirePullValueRequest, opts ...grpc.CallOption) (*WirePullValueResponse, error)
	SyncValue(ctx context.Context, in *pb.WireValue, opts ...grpc.CallOption) (*pb.MyBool, error)
}

type wireServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWireServiceClient(cc grpc.ClientConnInterface) WireServiceClient {
	return &wireServiceClient{cc}
}

func (c *wireServiceClient) Create(ctx context.Context, in *pb.Wire, opts ...grpc.CallOption) (*pb.Wire, error) {
	out := new(pb.Wire)
	err := c.cc.Invoke(ctx, WireService_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireServiceClient) Update(ctx context.Context, in *pb.Wire, opts ...grpc.CallOption) (*pb.Wire, error) {
	out := new(pb.Wire)
	err := c.cc.Invoke(ctx, WireService_Update_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireServiceClient) View(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.Wire, error) {
	out := new(pb.Wire)
	err := c.cc.Invoke(ctx, WireService_View_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireServiceClient) Name(ctx context.Context, in *WireNameRequest, opts ...grpc.CallOption) (*pb.Wire, error) {
	out := new(pb.Wire)
	err := c.cc.Invoke(ctx, WireService_Name_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireServiceClient) NameFull(ctx context.Context, in *pb.Name, opts ...grpc.CallOption) (*pb.Wire, error) {
	out := new(pb.Wire)
	err := c.cc.Invoke(ctx, WireService_NameFull_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireServiceClient) Delete(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.MyBool, error) {
	out := new(pb.MyBool)
	err := c.cc.Invoke(ctx, WireService_Delete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireServiceClient) List(ctx context.Context, in *WireListRequest, opts ...grpc.CallOption) (*WireListResponse, error) {
	out := new(WireListResponse)
	err := c.cc.Invoke(ctx, WireService_List_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireServiceClient) Clone(ctx context.Context, in *WireCloneRequest, opts ...grpc.CallOption) (*pb.MyBool, error) {
	out := new(pb.MyBool)
	err := c.cc.Invoke(ctx, WireService_Clone_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireServiceClient) GetValue(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.WireValue, error) {
	out := new(pb.WireValue)
	err := c.cc.Invoke(ctx, WireService_GetValue_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireServiceClient) SetValue(ctx context.Context, in *pb.WireValue, opts ...grpc.CallOption) (*pb.MyBool, error) {
	out := new(pb.MyBool)
	err := c.cc.Invoke(ctx, WireService_SetValue_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireServiceClient) SetValueUnchecked(ctx context.Context, in *pb.WireValue, opts ...grpc.CallOption) (*pb.MyBool, error) {
	out := new(pb.MyBool)
	err := c.cc.Invoke(ctx, WireService_SetValueUnchecked_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireServiceClient) GetValueByName(ctx context.Context, in *WireGetValueByNameRequest, opts ...grpc.CallOption) (*WireNameValue, error) {
	out := new(WireNameValue)
	err := c.cc.Invoke(ctx, WireService_GetValueByName_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireServiceClient) SetValueByName(ctx context.Context, in *WireNameValue, opts ...grpc.CallOption) (*pb.MyBool, error) {
	out := new(pb.MyBool)
	err := c.cc.Invoke(ctx, WireService_SetValueByName_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireServiceClient) SetValueByNameUnchecked(ctx context.Context, in *WireNameValue, opts ...grpc.CallOption) (*pb.MyBool, error) {
	out := new(pb.MyBool)
	err := c.cc.Invoke(ctx, WireService_SetValueByNameUnchecked_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireServiceClient) ViewWithDeleted(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.Wire, error) {
	out := new(pb.Wire)
	err := c.cc.Invoke(ctx, WireService_ViewWithDeleted_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireServiceClient) Pull(ctx context.Context, in *WirePullRequest, opts ...grpc.CallOption) (*WirePullResponse, error) {
	out := new(WirePullResponse)
	err := c.cc.Invoke(ctx, WireService_Pull_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireServiceClient) Sync(ctx context.Context, in *pb.Wire, opts ...grpc.CallOption) (*pb.MyBool, error) {
	out := new(pb.MyBool)
	err := c.cc.Invoke(ctx, WireService_Sync_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireServiceClient) ViewValue(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.WireValueUpdated, error) {
	out := new(pb.WireValueUpdated)
	err := c.cc.Invoke(ctx, WireService_ViewValue_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireServiceClient) DeleteValue(ctx context.Context, in *pb.Id, opts ...grpc.CallOption) (*pb.MyBool, error) {
	out := new(pb.MyBool)
	err := c.cc.Invoke(ctx, WireService_DeleteValue_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireServiceClient) PullValue(ctx context.Context, in *WirePullValueRequest, opts ...grpc.CallOption) (*WirePullValueResponse, error) {
	out := new(WirePullValueResponse)
	err := c.cc.Invoke(ctx, WireService_PullValue_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wireServiceClient) SyncValue(ctx context.Context, in *pb.WireValue, opts ...grpc.CallOption) (*pb.MyBool, error) {
	out := new(pb.MyBool)
	err := c.cc.Invoke(ctx, WireService_SyncValue_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WireServiceServer is the server API for WireService service.
// All implementations must embed UnimplementedWireServiceServer
// for forward compatibility
type WireServiceServer interface {
	Create(context.Context, *pb.Wire) (*pb.Wire, error)
	Update(context.Context, *pb.Wire) (*pb.Wire, error)
	View(context.Context, *pb.Id) (*pb.Wire, error)
	Name(context.Context, *WireNameRequest) (*pb.Wire, error)
	NameFull(context.Context, *pb.Name) (*pb.Wire, error)
	Delete(context.Context, *pb.Id) (*pb.MyBool, error)
	List(context.Context, *WireListRequest) (*WireListResponse, error)
	Clone(context.Context, *WireCloneRequest) (*pb.MyBool, error)
	GetValue(context.Context, *pb.Id) (*pb.WireValue, error)
	SetValue(context.Context, *pb.WireValue) (*pb.MyBool, error)
	SetValueUnchecked(context.Context, *pb.WireValue) (*pb.MyBool, error)
	GetValueByName(context.Context, *WireGetValueByNameRequest) (*WireNameValue, error)
	SetValueByName(context.Context, *WireNameValue) (*pb.MyBool, error)
	SetValueByNameUnchecked(context.Context, *WireNameValue) (*pb.MyBool, error)
	ViewWithDeleted(context.Context, *pb.Id) (*pb.Wire, error)
	Pull(context.Context, *WirePullRequest) (*WirePullResponse, error)
	Sync(context.Context, *pb.Wire) (*pb.MyBool, error)
	ViewValue(context.Context, *pb.Id) (*pb.WireValueUpdated, error)
	DeleteValue(context.Context, *pb.Id) (*pb.MyBool, error)
	PullValue(context.Context, *WirePullValueRequest) (*WirePullValueResponse, error)
	SyncValue(context.Context, *pb.WireValue) (*pb.MyBool, error)
	mustEmbedUnimplementedWireServiceServer()
}

// UnimplementedWireServiceServer must be embedded to have forward compatible implementations.
type UnimplementedWireServiceServer struct {
}

func (UnimplementedWireServiceServer) Create(context.Context, *pb.Wire) (*pb.Wire, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedWireServiceServer) Update(context.Context, *pb.Wire) (*pb.Wire, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedWireServiceServer) View(context.Context, *pb.Id) (*pb.Wire, error) {
	return nil, status.Errorf(codes.Unimplemented, "method View not implemented")
}
func (UnimplementedWireServiceServer) Name(context.Context, *WireNameRequest) (*pb.Wire, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Name not implemented")
}
func (UnimplementedWireServiceServer) NameFull(context.Context, *pb.Name) (*pb.Wire, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NameFull not implemented")
}
func (UnimplementedWireServiceServer) Delete(context.Context, *pb.Id) (*pb.MyBool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedWireServiceServer) List(context.Context, *WireListRequest) (*WireListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedWireServiceServer) Clone(context.Context, *WireCloneRequest) (*pb.MyBool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Clone not implemented")
}
func (UnimplementedWireServiceServer) GetValue(context.Context, *pb.Id) (*pb.WireValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetValue not implemented")
}
func (UnimplementedWireServiceServer) SetValue(context.Context, *pb.WireValue) (*pb.MyBool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetValue not implemented")
}
func (UnimplementedWireServiceServer) SetValueUnchecked(context.Context, *pb.WireValue) (*pb.MyBool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetValueUnchecked not implemented")
}
func (UnimplementedWireServiceServer) GetValueByName(context.Context, *WireGetValueByNameRequest) (*WireNameValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetValueByName not implemented")
}
func (UnimplementedWireServiceServer) SetValueByName(context.Context, *WireNameValue) (*pb.MyBool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetValueByName not implemented")
}
func (UnimplementedWireServiceServer) SetValueByNameUnchecked(context.Context, *WireNameValue) (*pb.MyBool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetValueByNameUnchecked not implemented")
}
func (UnimplementedWireServiceServer) ViewWithDeleted(context.Context, *pb.Id) (*pb.Wire, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ViewWithDeleted not implemented")
}
func (UnimplementedWireServiceServer) Pull(context.Context, *WirePullRequest) (*WirePullResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Pull not implemented")
}
func (UnimplementedWireServiceServer) Sync(context.Context, *pb.Wire) (*pb.MyBool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sync not implemented")
}
func (UnimplementedWireServiceServer) ViewValue(context.Context, *pb.Id) (*pb.WireValueUpdated, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ViewValue not implemented")
}
func (UnimplementedWireServiceServer) DeleteValue(context.Context, *pb.Id) (*pb.MyBool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteValue not implemented")
}
func (UnimplementedWireServiceServer) PullValue(context.Context, *WirePullValueRequest) (*WirePullValueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PullValue not implemented")
}
func (UnimplementedWireServiceServer) SyncValue(context.Context, *pb.WireValue) (*pb.MyBool, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncValue not implemented")
}
func (UnimplementedWireServiceServer) mustEmbedUnimplementedWireServiceServer() {}

// UnsafeWireServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WireServiceServer will
// result in compilation errors.
type UnsafeWireServiceServer interface {
	mustEmbedUnimplementedWireServiceServer()
}

func RegisterWireServiceServer(s grpc.ServiceRegistrar, srv WireServiceServer) {
	s.RegisterService(&WireService_ServiceDesc, srv)
}

func _WireService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Wire)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireServiceServer).Create(ctx, req.(*pb.Wire))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Wire)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireServiceServer).Update(ctx, req.(*pb.Wire))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireService_View_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireServiceServer).View(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireService_View_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireServiceServer).View(ctx, req.(*pb.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireService_Name_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WireNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireServiceServer).Name(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireService_Name_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireServiceServer).Name(ctx, req.(*WireNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireService_NameFull_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Name)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireServiceServer).NameFull(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireService_NameFull_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireServiceServer).NameFull(ctx, req.(*pb.Name))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireServiceServer).Delete(ctx, req.(*pb.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WireListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireServiceServer).List(ctx, req.(*WireListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireService_Clone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WireCloneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireServiceServer).Clone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireService_Clone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireServiceServer).Clone(ctx, req.(*WireCloneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireService_GetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireServiceServer).GetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireService_GetValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireServiceServer).GetValue(ctx, req.(*pb.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireService_SetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.WireValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireServiceServer).SetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireService_SetValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireServiceServer).SetValue(ctx, req.(*pb.WireValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireService_SetValueUnchecked_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.WireValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireServiceServer).SetValueUnchecked(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireService_SetValueUnchecked_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireServiceServer).SetValueUnchecked(ctx, req.(*pb.WireValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireService_GetValueByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WireGetValueByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireServiceServer).GetValueByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireService_GetValueByName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireServiceServer).GetValueByName(ctx, req.(*WireGetValueByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireService_SetValueByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WireNameValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireServiceServer).SetValueByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireService_SetValueByName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireServiceServer).SetValueByName(ctx, req.(*WireNameValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireService_SetValueByNameUnchecked_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WireNameValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireServiceServer).SetValueByNameUnchecked(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireService_SetValueByNameUnchecked_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireServiceServer).SetValueByNameUnchecked(ctx, req.(*WireNameValue))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireService_ViewWithDeleted_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireServiceServer).ViewWithDeleted(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireService_ViewWithDeleted_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireServiceServer).ViewWithDeleted(ctx, req.(*pb.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireService_Pull_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WirePullRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireServiceServer).Pull(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireService_Pull_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireServiceServer).Pull(ctx, req.(*WirePullRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireService_Sync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Wire)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireServiceServer).Sync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireService_Sync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireServiceServer).Sync(ctx, req.(*pb.Wire))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireService_ViewValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireServiceServer).ViewValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireService_ViewValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireServiceServer).ViewValue(ctx, req.(*pb.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireService_DeleteValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.Id)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireServiceServer).DeleteValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireService_DeleteValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireServiceServer).DeleteValue(ctx, req.(*pb.Id))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireService_PullValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WirePullValueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireServiceServer).PullValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireService_PullValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireServiceServer).PullValue(ctx, req.(*WirePullValueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WireService_SyncValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(pb.WireValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WireServiceServer).SyncValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WireService_SyncValue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WireServiceServer).SyncValue(ctx, req.(*pb.WireValue))
	}
	return interceptor(ctx, in, info, handler)
}

// WireService_ServiceDesc is the grpc.ServiceDesc for WireService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WireService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cores.WireService",
	HandlerType: (*WireServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _WireService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _WireService_Update_Handler,
		},
		{
			MethodName: "View",
			Handler:    _WireService_View_Handler,
		},
		{
			MethodName: "Name",
			Handler:    _WireService_Name_Handler,
		},
		{
			MethodName: "NameFull",
			Handler:    _WireService_NameFull_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _WireService_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _WireService_List_Handler,
		},
		{
			MethodName: "Clone",
			Handler:    _WireService_Clone_Handler,
		},
		{
			MethodName: "GetValue",
			Handler:    _WireService_GetValue_Handler,
		},
		{
			MethodName: "SetValue",
			Handler:    _WireService_SetValue_Handler,
		},
		{
			MethodName: "SetValueUnchecked",
			Handler:    _WireService_SetValueUnchecked_Handler,
		},
		{
			MethodName: "GetValueByName",
			Handler:    _WireService_GetValueByName_Handler,
		},
		{
			MethodName: "SetValueByName",
			Handler:    _WireService_SetValueByName_Handler,
		},
		{
			MethodName: "SetValueByNameUnchecked",
			Handler:    _WireService_SetValueByNameUnchecked_Handler,
		},
		{
			MethodName: "ViewWithDeleted",
			Handler:    _WireService_ViewWithDeleted_Handler,
		},
		{
			MethodName: "Pull",
			Handler:    _WireService_Pull_Handler,
		},
		{
			MethodName: "Sync",
			Handler:    _WireService_Sync_Handler,
		},
		{
			MethodName: "ViewValue",
			Handler:    _WireService_ViewValue_Handler,
		},
		{
			MethodName: "DeleteValue",
			Handler:    _WireService_DeleteValue_Handler,
		},
		{
			MethodName: "PullValue",
			Handler:    _WireService_PullValue_Handler,
		},
		{
			MethodName: "SyncValue",
			Handler:    _WireService_SyncValue_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cores/cable_service.proto",
}
